[[redirects]]
from = "/*"
to = "/src/index.html"
status = 200
conditions = { "Path" : { "regex" : "^(?!/src/index.html|src/img/)" } }

[[redirects]]
from = "src/img/*"
to = "src/img/:splat"
status = 200
